# Generated by Django 2.1.15 on 2020-11-04 08:58

import cosmossqlapp.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('address', djongo.models.fields.EmbeddedField(model_container=cosmossqlapp.models.Address)),
            ],
        ),
    ]
